/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
    export interface GlobalComponents {
        AAvatar: typeof import('@arco-design/web-vue')['Avatar']
        ABreadcrumb: typeof import('@arco-design/web-vue')['Breadcrumb']
        ABreadcrumbItem: typeof import('@arco-design/web-vue')['BreadcrumbItem']
        AButton: typeof import('@arco-design/web-vue')['Button']
        AInput: typeof import('@arco-design/web-vue')['Input']
        AInputGroup: typeof import('@arco-design/web-vue')['InputGroup']
        ALayout: typeof import('@arco-design/web-vue')['Layout']
        ALayoutContent: typeof import('@arco-design/web-vue')['LayoutContent']
        ALayoutFooter: typeof import('@arco-design/web-vue')['LayoutFooter']
        ALayoutHeader: typeof import('@arco-design/web-vue')['LayoutHeader']
        ALayoutSider: typeof import('@arco-design/web-vue')['LayoutSider']
        ALink: typeof import('@arco-design/web-vue')['Link']
        AMenu: typeof import('@arco-design/web-vue')['Menu']
        AMenuItem: typeof import('@arco-design/web-vue')['MenuItem']
        ASubMenu: typeof import('@arco-design/web-vue')['SubMenu']
        ASwitch: typeof import('@arco-design/web-vue')['Switch']
        NButton: typeof import('naive-ui')['NButton']
        NInput: typeof import('naive-ui')['NInput']
        NSpace: typeof import('naive-ui')['NSpace']
        RouterLink: typeof import('vue-router')['RouterLink']
        RouterView: typeof import('vue-router')['RouterView']
    }
}
